name: "ghapi - Create Label on Comment"

on:
    pull_request:

permissions:
    contents: read
    issues: write
    pull-requests: write

jobs:
    ghapi:
        if: contains(github.event.comment.body, '/bug')
        runs-on: ubuntu-latest
        steps:
            - name: Install Dependencies
              run: pip install ghapi

            - name: Create a label
              shell: python
              run: |
                  import os
                  from ghapi.code import GhApi
                  owner, repo = os.environ['REPO'].split("/")
                  api = GhApi(owner=owner, repo=repo)
                  api.issues.add_labels(owner, repo, os.environ['NUMBER'], 'bug')
              env:
                  NUMBER: ${{ github.event.number }}
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  REPO: ${{ github.repository }}
