name: "Unit Test"
on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    unit-test:
        runs-on: ubuntu-latest
        steps:
            - name: Copy Repository Contents
              uses: actions/checkout@v3

            - name: Run unit-test on sortColors
              run: |
                  pip install -U pytest
                  pytest Assignment-1/
