name: "Baseline vs New Model"
on:
    issue_comment:
permissions:
    contents: read
    issues: write
    pull-requests: write
jobs:
    wandb-compare:
        if: (github.event.issue.pull_request != null) && contains(github.event.comment.body, '/wand')
        runs-on: ubuntu-latest
        steps:
            - name: Get repo contents
              uses: actions/checkout@v3

            - name: Install dependencies
              run: pip install ghapi wandb

            - name: Parse value from the comment
              id: check-match
              shell: python
              run: |
                  import re, os
                  comment = os.getenv('PR_COMMENT', '')
                  pattern = r"/wandb[\s]+(\w+)"
                  match = re.findall(pattern, comment)
                  with open(os.environ['GITHUB_OUTPUT'], 'a') as handle:
                    if len(match) > 0:
                        print(f'FOUND=true', file=handle)
                        print(f'ID={match}', file=handle)
                    else:
                        print(f'FOUND=false', file=handle)
              env:
                  PR_COMMENT: ${{ github.event.comment.body }}

            - name: Create Comparison Report
              if: ${{ steps.check-match.outputs.FOUND == 'true' }}
              id: comparison-report
              run: python ./Assignment-3/compare_runs.py
              env:
                  WANDB_ENTITY: sagar118
                  WANDB_PROJECT: cicd-quickstart
                  BASELINE_TAG: baseline
                  RUN_ID: "${{ steps.check-match.outputs.ID }}"
                  WANDB_API_KEY: ${{ secrets.WANDB_API_KEY }}

#             - name: Make Comment in PR
#               uses: actions/github-script@v6
#               if: steps.comparison-report.outcome == 'success'
#               with:
#                   script: |
#                       var msg = `A comparison between the linked run and baseline is available [in this report](${process.env.REPORT_URL})`
#                       github.rest.issues.createComment({
#                           owner: context.repo.owner,
#                           repo: context.repo.repo,
#                           issue_number: context.issue.number,
#                           body: msg,
#                       });
#               env:
#                   REPORT_URL: "${{ steps.comparison-report.outputs.REPORT_URL }}"
